import org.junit.Test;

import de.katzen48.hetznercloudjava.HetznerCloud;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Startrekfreak' at '24.01.18 06:47' with Gradle 2.9
 *
 * @author Startrekfreak, @date 24.01.18 06:47
 */
public class APITest 
{
    @Test public void testAPIConnection() 
    {
        HetznerCloud cloud = new HetznerCloud.Builder().withToken("FooBar").build();
        assertNotNull("getServers() should return some List", cloud.getServers());
        System.out.println(cloud.getServers().length);
        System.out.flush();
    }
}
